### ISSUE TITLE
Infinite loop on clip

### ISSUE THREAD

**Issue by raovgarimella** [devonmpowell/r3d#15]
I have encountered a case where the R3D code is getting stuck in an infinite loop when executing the clip algorithm. The polyhedron being clipped is non-convex. The clipping faces come from a tet. There seem to be two issues:

 r3d_init_poly produces an odd result. When I look at the poly, the first few entries are

```
(gdb) p poly1
$8 = {verts = {{**pnbrs = {0, 0, 1}**, pos = {{x = 0.14644370973110207, 
          y = 0.01442344579845665, z = 2.9953535795211801}, xyz = {
          0.14644370973110207, 0.01442344579845665, 2.9953535795211801}}}, {
      **pnbrs = {0, 1, 1}**, pos = {{x = 0.14644370973110207, 
          y = 0.01442344579845665, z = 2.9953535795211801}, xyz = {
          0.14644370973110207, 0.01442344579845665, 2.9953535795211801}}}, {
      pnbrs = {3, 112, 4}, pos = {{x = 0.14644370973110207, 
          y = 0.01442344579845665, z = 2.9953535795211801}, xyz = {
          0.14644370973110207, 0.01442344579845665, 2.9953535795211801}}}, {
      **pnbrs = {1, 2, 2}**, pos = {{x = 0.14644370973110207, 
          y = 0.01442344579845665, z = 2.9953535795211801}, xyz = {
          0.14644370973110207, 0.01442344579845665, 2.9953535795211801}}}, {
```

During the actual clipping, the algorithm is in an infinite loop at vertex 48. Vertex 48 thinks of itself as its own neighbor and that causes an infinite loop at line 100 of r3d.c

(gdb) p vertbuffer[vnext]
$50 = {pnbrs = {48, 48, 104}, pos = {{x = 0.012418896627257769, 
      y = 0.12609117821246149, z = 2.9764227609370937}, xyz = {
      0.012418896627257769, 0.12609117821246149, 2.9764227609370937}}}

A reproducer is attached in the form of a tar file. It contains the code with the latest r3d embedded as subdirectory. It also contains the two polygon data files. 
You can compile it as
```
gcc -g main.c r3d/r3d.c -o chkintr3d -lm
```
and run it as
```
./chkintr3d srpoly.dat tet.dat
```

An image of the two polyhedra is also attached.
[
![problem](https://user-images.githubusercontent.com/16911552/106524390-bdb0f280-649f-11eb-8fad-6fe9b5f6b5de.png)
[reproducer.tar.gz](https://github.com/devonmpowell/r3d/files/5907069/reproducer.tar.gz)

](url)

**Comment by devonmpowell** [comment]
Nice to hear from you, Rao.
This is definitely a bug in r3d_init_poly. The fact that the first few vertices have degenerate pointers tells me that something is going wrong with the topology here when assembling the vertex graph from the boundary representation.  So, it does not surprise me that the clip routine fails, as it expects only valid inputs.
Let me take a look in the next couple of days.

**Comment by raovgarimella** [comment]
Thank you Devon. I will try to stare at it too but you probably can figure it out faster.

**Comment by devonmpowell** [comment]
After taking a look, I think that this might be a problem with the input polyhedron rather than `r3d_init_poly`.  To illustrate, when I add the following print at line 804 of r3d.c (after degenerate vertices are created but not yet linked):

```
            for (v = 0; v < eperv[0]; ++v) {   
			        printf("Vert %d, pos = %f %f %f, pnbrs = %d %d %d\n", v,   
					        vbtmp[v].pos.x, vbtmp[v].pos.y, vbtmp[v].pos.x,    
					        vbtmp[v].pnbrs[0], vbtmp[v].pnbrs[1], vbtmp[v].pnbrs[2]);   
		        }   
```
the output is as follows:
```
        Vert 0, pos = 0.146444 0.014423 0.146444, pnbrs = 512 2 1   
        Vert 1, pos = 0.146444 0.014423 0.146444, pnbrs = 512 4 2   
        Vert 2, pos = 0.146444 0.014423 0.146444, pnbrs = 512 1 8   
        Vert 3, pos = 0.146444 0.014423 0.146444, pnbrs = 512 8 10   
        Vert 4, pos = 0.146444 0.014423 0.146444, pnbrs = 512 14 13   
        Vert 5, pos = 0.146444 0.014423 0.146444, pnbrs = 512 4 14   
        Vert 6, pos = 0.146444 0.014423 0.146444, pnbrs = 512 13 16   
        Vert 7, pos = 0.146444 0.014423 0.146444, pnbrs = 512 16 10   
```

Note that the pointers to vertices 4 and 10 point in the same direction from the dummy vertices containing them.  This tells me that some of the faces of the input poly are oriented opposite to others (CW vs CCW). This is what seems to be breaking `r3d_init_poly()`.

So perhaps you could double-check the creation of srcpoly.dat?

**Comment by raovgarimella** [comment]
OK, I will investigate. I distilled a polyhedron from a larger problem and put it through several steps to create the reproducer, so I will look where it might be occurring. Thank you for your quick response.

**Comment by raovgarimella** [comment]
Devon
The data I gave you was bad. Here is some (I hope) correct data 
[reproducer.tar.gz](https://github.com/devonmpowell/r3d/files/5930251/reproducer.tar.gz)
that results in an infinite loop.
Thanks
Rao

**Comment by devonmpowell** [comment]
Hi Rao,
This one appears to work.  I think `r3d_init_poly()` is fine, but `r3d_clip()` must need more than 512 vertices in its buffer at some intermediate step.  I just had to increase `R3D_MAX_VERTS` to 1024. 
Let me know if this works for you as well.

**Comment by raovgarimella** [comment]
I can confirm that with the 512 limit on R3D_MAX_VERTS, r3d_clip got stuck but with the 1024 limit, it completed. It was likely overwriting something. I think it would be good to have a check that we exceeded the preset limit.

**Comment by raovgarimella** [comment]
Also, any thoughts on making a variant that uses variable length arrays and removes the trivalent vertex restriction? I know you said previously that you did it because of the potential gains from compiler optimization when it sees fixed length loops. However, in our profiling (if my memory serves me right), r3d_init_poly is not insignificant. Also, dealing with an increased number of vertices could be offsetting the gains you may be getting from loop unrolling and other compiler optimizations. (I've attached the results of one of our runs - r3d clip dominates of course, but r3d_init_poly is not trivial). Of course, there is only one way to know which is better - have someone do a head to head comparison of the two implementations.

I am almost tempted to make a summer student do this. What do you think?

**Comment by raovgarimella** [comment]
Also, would you be interested in increasing R3D_MAX_VERTS to 1024 in the mainline code? How badly do you think it will affect the memory footprint? The alternative could be to make it a compile definition that one can set - maybe a switch that says use larger limits using a switch like R3D_ALLOW_LARGE_POLYS or something.

**Comment by devonmpowell** [comment]
All of your suggestions are good ones. I think they would really help the usability of the code. The biggest improvement is that the code does not fail silently, and a few if-statements would surely not cause any performance penalty.
If you were to have a student help out with this, I would be happy to be in touch and provide some guidance.
Cheers,
Devon

**Comment by raovgarimella** [comment]
Thank you for your offer to help. I will let you know if we can find someone (all students are working remotely again this year). I will issue a PR if I can make some of the smaller improvements myself. It's up to you whether you want to close out this issue or leave it open until such time as those little fixes are made.

**Comment by devonmpowell** [comment]
Of course, always happy to help.
I am going to close this issue. It is not a specific code bug per se, but rather a potential improvement in design philosophy that you, I and the other LANL folks are all aware of. Let's keep in touch over this.

**Comment by raovgarimella** [comment]
If I put in a check on violating the max buffer size, what would your preferred method be for signalling an error?
Will an fprintf to stderr and an exit with (-1) be ok?

Or do you want the routines to return an error code that the calling app has to check?
