### ISSUE TITLE
Update Spack recipe for R3D

### ISSUE THREAD

**Issue by raovgarimella** [devonmpowell/r3d#28]
We need to update the spack recipe for R3D to account for the latest version. Complicating this issue is that old versions use Make and the new version uses CMake

**Comment by raovgarimella** [comment]
There is now a pending [PR](https://github.com/spack/spack/pull/22327) on Spack that adheres to their guidelines, passes all their checks and also enables installation of both the old and new (2021-03-16) versions. The new version has a variant that allows for R3D_MAX_VERTS to be changed using the ```maxverts=nnnnn``` specification.

@denissen-lanl

**Comment by denissen-lanl** [comment]
@raovgarimella thanks for sticking with this!
