### ISSUE TITLE
Mesh voxelization code

### ISSUE THREAD

**Issue by dionhaefner** [devonmpowell/r3d#35]
Is there code available for the voxelization of entire meshes as in Powell and Abel, 2015?

For example the code that produced this figure:

![1-s2 0-S0021999115003563-gr008_lrg](https://github.com/devonmpowell/r3d/assets/11994217/443d262f-f06a-4cff-9602-42bb073757c3)

I'm particularly interested in how to use higher-order moments for this.

**Comment by dionhaefner** [comment]
If you can't share the original code, I would still be interested in how to use higher-order moments for voxelization. Any pointers / algorithm outline would be helpful.

**Comment by devonmpowell** [comment]
The figure in Powell and Abel, 2015 was made using a much older, now deprecated version of this code that had a pretty obtuse API. So I am not sure it would be any help to you. 

I recommend taking a look at `v3d.c` and `v3d.h`, which handle the special case of voxelizing cells to a Cartesian grid.  There is no function in `r3d` that will voxelize an entire mesh, as it would require some assumption on the format of the input mesh. So, we leave responsibility to the user to write their own loop over mesh cells, and provide them to `r3d_voxelize` in the correct `r3d_poly`. Hopefully that makes sense.

**Comment by dionhaefner** [comment]
Yea that's what I'm doing, and with #34 out of the way this works very well. The thing I'm still fuzzy about is using order > 0. Maybe I misunderstand something; would this allow me to do for example linear interpolation for target grid cells that undersample the original mesh?

**Comment by devonmpowell** [comment]
Yes, what you describe should be fairly straightforward. The ordering of cells in the voxel grid is (i,j,k,m) indexed in C-order, so for any i,j,k you can get e.g. the first-order moments like $\int \rho x d^3x$ over each voxel.  Once you have the center of mass in each voxel, the corresponding linear interpolant giving the same CM should be easy enough to compute.

**Comment by dionhaefner** [comment]
Thanks, I'll let that sizzle for a bit.

**Comment by devonmpowell** [comment]
The center of mass was just an example; really you could do it for any quantity (specific momentum, internal energy, etc). The basic idea is to construct the interpolant such that the integral of the interpolant within a voxel has the same moments as the voxelized quantity.
