### ISSUE TITLE
Polyhedron clipping

### ISSUE THREAD

**Issue by chapouvalpin** [devonmpowell/r3d#6]
Hi,
I am interested in the implementation of the Sugihara's clipping algorithm.
I like the idea to place higher priority to topological consistency.
In your implementation, the triply-connectedness property is checked after the clipping process but not during the vertex partitioning process. 
In [Sugihara 1994], the vertices are classified sequentially using the following rules:
"If condition (C1) implies a unique classification, we follow this", otherwise the distance to the plane is used.
Do you have any idea or reference on which algorithm to use to check the (C1) condition [Sugihara 1994] during the vertex partitioning?
Thanks for you help.
Antoine

**Comment by devonmpowell** [comment]
Hi Antoine,

My implementation assumes that the input is correct (i.e.
triply-connected).  But, there are no actual checks in my implementation.
The clipping and vertex partitioning processes are designed to
automatically preserve the topoligical validity of the input.

I am not sure that Condition C1 applies in this context.  If you read the
LA-UR pdf in the github repo, you'll see that we treat each connected
component of the resulting partitioned graph separately.
So there are no special cases needed here.

I hope that helps,
Devon

**Comment by chapouvalpin** [comment]
Hi Devon,

Thanks for your prompt reply. Reading the LA-UR PDF helps me to understand. In section 3.2, you explain that you slightly modify the Sugihara's algorithm to handle non-convex polyhedra.
Even if the input polyhedron is a convex polyhedron (in the sense that its edge-vertex graph is planar and triply connected), your algorithm may generate a multiply-connected polyhedron instead of forcing the output polyhedron to be convex. Thus the C1 condition is not required in this context.

Thanks again,
Antoine
